config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#index"
  # get "/articles", to: "pages#index"
  # get "/demo", to: "pages#demo"

  # get "/articles/:id", to: "pages#show"

  resources :pages do 
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :page
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :comments
  
  validates :title, presence: true
  validates :body, presence: true, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Page.find(params[:page_id])
    @comment = @article.comments.create(comment_params)
    redirect_to page_path(@article)
  end

  private
    def comment_params
      params.require(:comment).permit(:user, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @articles = Page.all
  end

  def demo
    @arr = [1,2,3,4]
  end

  def show
    @article = Page.find(params[:id])
  end

  def new
    @article = Page.new
  end

  def create
    @article = Page.new(article_params)

    if @article.save
      redirect_to  @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Page.find(params[:id])
  end

  def update
    @article = Page.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Page.find(params[:id])
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def article_params
      params.require(:page).permit(:title, :body)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comments/_comment.htm.erb
<div>
  <strong>User</strong>
  <%= comment.user%>
</div>

<div>
  <strong>Body</strong>
  <%= comment.body%>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :user %><br>
      <%= form.text_field :user %>
    </p>
    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>
    <p>
      <%= form.submit %>
    </p>
<% end %>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pro</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/_form.html.erb
<h1>NEw Form</h1>

<%= form_with model: page do |form| %>
  <div>
    <%= form.label :title%><br>
    <%= form.text_field :title %><br>

    <% page.errors.full_messages_for(:title).each do |message| %>
      
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body%><br>
    <%= form.text_area :body %><br>

    <% page.errors.full_messages_for(:body).each do |message| %>
      
      <div><%= message %></div>
    <% end %>

  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/demo.html.erb
<h1>demo route</h1>


 <% @arr.each do |val| %>
    <%= val%>

    <%end%>

app/views/pages/edit.html.erb
<h1>Edit Article</h1>

<%= render "form", page: @article%>

app/views/pages/index.html.erb
<h1>Hello, Rails!</h1>

<h3>This is Article data</h3>

<ul>
  <% @articles.each do |article|%>
    <li>
      <%= link_to article.title, article%>
    </li>
  <% end %>
</ul>

<%= link_to "New Article", new_page_path %>

app/views/pages/new.html.erb
<h1>NEw Article</h1>

<%= render "form", page: @article%>

app/views/pages/show.html.erb
<h1>This is show</h1>

<h4><%= @article.title %></h4>

<p><%= @article.body %></p>

<ul>
  <li><%= link_to "Home", root_path%></li>    
  <li><%= link_to "Edit", edit_page_path(@article)%></li>
  <li><%= link_to "Delete", page_path(@article), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %></li>
</ul>

<h3>Comments</h3>
<% @article.comments.each do |comment|%>
   <div><%= comment.user %></div>
   <div><%= comment.body %></div>
<% end%>





<h2>Add Comments</h2>
<%= form_with model: [@article, @article.comments.build ] do |form| %><br>
  <div>
    <%= form.label :user %><br>
    <%= form.text_field :user%>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body%>
  </div>

  <div><%= form.submit %></div>
<% end %>